In [24]:
upper=int(input("enter min num"))
lower=int(input("enter max num"))
a=range(upper,lower+1)
res=list(filter(lambda x: (x%2==0 and x>0) ,a))
print(res)

enter min num-6
enter max num10
[2, 4, 6, 8, 10]


# DEFINE AN ENGLISH TO FRENCH TRANSLATOR FUNCTION THAT TAKES AN INPUT FROM A USER AND RETURNS THE TRANSLATION, USE ANY 5 KNOWN WORDS
 

{'happy': 'heureux', 
             'success': 'Succès', 
             'studying': 'en train d\'étudier',
             'traveling': 'en voyageant',
             'love': 'amour'}

In [31]:
a={'happy': 'heureux', 
             'success': 'Succès', 
             'studying': 'en train d\'étudier',
             'traveling': 'en voyageant',
             'love': 'amour'}

In [3]:
def engtofre():
    for i in a:
        french=input("enter french ")
        if french=='heureux':
            print("english translate:Happy")
    
       
        elif french=='en train d\'étudier':
            print("english treanslate: Studying")
        elif french=='Succès':
            print("english treanslate: success")
        elif french=='en voyageant':
            print("english treanslate: travelling")
        elif french=="amour":
            print("english treanslate: love ")
        else:
            print("enter french")
        
        

In [ ]:
engtofre()


enter french heureux
english translate:Happy
enter french heureux
english translate:Happy
enter french amour
english treanslate: love 
enter french xyz
enter french


In [6]:
def trans(word):
    if word in a:
        return a[word]
    else:
        print("dictionary doesnt contain this word")
        

In [8]:
trans("happy")

'heureux'

In [25]:

    t=lambda word: a[word] if word in a else"not in dictionary"
    t("Saurabh")
    

'not in dictionary'

In [32]:
def engtofre(word):
    try:
        return a[word]
    except keyError:
        return 'not in dictionary'

In [36]:
ina=input("enter english:")
engtofre(ina)

enter english:studying


"en train d'étudier"

In [54]:
import numpy as np
a=np.array(([1,1],[2,2]))
b=np.array(([3,3],[4,4]))
def matrix_operations(a, b):
  
    print ("Matrices Addition = \n", np.add(a, b)) 
  
    print ("Matrices Subtraction = \n", np.subtract(a, b)) 
  
    print ("Matrices Multiplication = \n", np.divide(a, b)) 
 
    print ("Matrix A Transpose = \n", a.T) 
    
    print ("Matrix B Transpose = \n", b.T) 
 
    print ("Element by element multiplication = \n", np.multiply(a,b)) 
 
    print ("Matrices Product = \n", np.dot(a,b)) 
 
    print ("Element by element square root = \n", np.sqrt(a)) 
 
    print ("Summation of all matrix elements A = \n", np.sum(a))  
    
    print ("Summation of all matrix elements B = \n", np.sum(b)) 
 
    print ("Column wise summation of matrix A = \n ", np.sum(a, axis = 0)) 
  
    print ("Row wise summation of matrix A = \n", np.sum(a, axis = 1))

In [57]:
np.shape(a)

(2, 2)

In [55]:
matrix_operations(a, b)

Matrices Addition = 
 [[4 4]
 [6 6]]
Matrices Subtraction = 
 [[-2 -2]
 [-2 -2]]
Matrices Multiplication = 
 [[0.33333333 0.33333333]
 [0.5        0.5       ]]
Matrix A Transpose = 
 [[1 2]
 [1 2]]
Matrix B Transpose = 
 [[3 4]
 [3 4]]
Element by element multiplication = 
 [[3 3]
 [8 8]]
Matrices Product = 
 [[ 7  7]
 [14 14]]
Element by element square root = 
 [[1.         1.        ]
 [1.41421356 1.41421356]]
Summation of all matrix elements A = 
 6
Summation of all matrix elements B = 
 14
Column wise summation of matrix A = 
  [3 3]
Row wise summation of matrix A = 
 [2 4]


In [58]:
import pandas as pd


In [62]:
df=pd.read_excel("C:/Users/Admin/Desktop/Saurabh/saurabh.xlsx")

In [63]:
df

quantity  \
0                                        30   
1                                        42   
2                                        95   
3                                     total   
4                                   average   
5                                     count   
6                                       NaN   
7   concat combines or joins two statements   
8                                     hello   
9                                helloworld   
10                              hello world   
11                                      NaN   
12                                      now   
13               2023-09-28 08:48:34.600000   
14                                        8   
15                                       48   
16                                      NaN   
17                                      NaN   
18                             IF CONdition   
19                                      NaN   
20                                       60   
21                                       45   
22                                       50   
23                                      NaN   
24                                    false   

                                      price  \
0                                       100   
1                                       200   
2                                       300   
3                                       NaN   
4                                       NaN   
5                                       NaN   
6                                       NaN   
7   concat combines or joins two statements   
8                                     world   
9                                       NaN   
10                                      NaN   
11                                      NaN   
12                                    today   
13                      2023-09-28 00:00:00   
14                                        9   
15                                       28   
16                      2023-09-21 00:00:00   
17                                      NaN   
18                                      NaN   
19                                      NaN   
20                                    false   
21                                     true   
22                                     true   
23                                      NaN   
24                                      NaN   

                                total sales  Unnamed: 3 Unnamed: 4  \
0                                      3000      3000.0        NaN   
1                                      8400      8400.0        NaN   
2                                     28500     28500.0        NaN   
3                                     39900         NaN        NaN   
4                                     13300     13300.0        NaN   
5                                         3         NaN        NaN   
6                                       NaN         NaN        NaN   
7   concat combines or joins two statements         NaN     length   
8                                       NaN         NaN          5   
9                                       NaN         NaN         10   
10                                      NaN         NaN         11   
11                                      NaN         NaN        NaN   
12                                      NaN         NaN       TIME   
13                                     2023         NaN   08:45:00   
14                                      NaN         NaN   13:01:04   
15                                      NaN         NaN        NaN   
16                                      NaN         NaN        NaN   
17                                      NaN         NaN        NaN   
18                                   ifelse         NaN        NaN   
19                                      NaN         NaN        NaN   
20                                      NaN         NaN        NaN   
21                                      NaN      

In [67]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 

In [72]:
df.shape

(25, 18)

In [76]:
df.head(8)

quantity  \
0                                       30   
1                                       42   
2                                       95   
3                                    total   
4                                  average   
5                                    count   
6                                      NaN   
7  concat combines or joins two statements   

                                     price  \
0                                      100   
1                                      200   
2                                      300   
3                                      NaN   
4                                      NaN   
5                                      NaN   
6                                      NaN   
7  concat combines or joins two statements   

                               total sales  Unnamed: 3 Unnamed: 4  \
0                                     3000      3000.0        NaN   
1                                     8400      8400.0        NaN   
2                                    28500     28500.0        NaN   
3                                    39900         NaN        NaN   
4                                    13300     13300.0        NaN   
5                                        3         NaN        NaN   
6                                      NaN         NaN        NaN   
7  concat combines or joins two statements         NaN     length   

  modulus(returns the remainder)  Unnamed: 6 Unnamed: 7  Unnamed: 8  \
0                             10           0        NaN         NaN   
1                             26           6        NaN         NaN   
2                             34           4        NaN         NaN   
3                            NaN         NaN        NaN         NaN   
4                            NaN         NaN        NaN         NaN   
5                            NaN         NaN        NaN         NaN   
6                            NaN         NaN        NaN         NaN   
7                            NaN  substitute        NaN         NaN   

            power  Unnamed: 10  celing Unnamed: 12  Unnamed: 13 Unnamed: 14  \
0             100          NaN  35.956          36          NaN         NaN   
1             676          NaN  22.343          25          NaN         NaN   
2            1156          NaN    91.6          92          NaN         NaN   
3             NaN          NaN     NaN         NaN          NaN         NaN   
4             NaN          NaN     NaN         NaN          NaN         NaN   
5             NaN          NaN     NaN         NaN          NaN         NaN   
6             NaN          NaN     NaN         NaN          NaN         NaN   
7  left,mid,right          NaN     NaN         NaN          NaN         NaN   

    floor Unnamed: 16 Unnamed: 17  
0  35.956          35         NaN  
1  22.343          22         NaN  
2  91.642          90         NaN  
3     NaN         NaN         NaN  
4     NaN         NaN         NaN  
5     NaN         NaN         NaN  
6     NaN         NaN         NaN  
7     NaN         NaN         NaN

In [77]:
df.columns

Index(['quantity', 'price', 'total sales', 'Unnamed: 3', 'Unnamed: 4',
       'modulus(returns the remainder)', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'power', 'Unnamed: 10', 'celing', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'floor', 'Unnamed: 16', 'Unnamed: 17'],
      dtype='object')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   quantity                        19 non-null     object 
 1   price                           13 non-null     object 
 2   total sales                     9 non-null      object 
 3   Unnamed: 3                      4 non-null      float64
 4   Unnamed: 4                      7 non-null      object 
 5   modulus(returns the remainder)  5 non-null      object 
 6   Unnamed: 6                      9 non-null      object 
 7   Unnamed: 7                      1 non-null      object 
 8   Unnamed: 8                      0 non-null      float64
 9   power                           7 non-null      object 
 10  Unnamed: 10                     0 non-null      float64
 11  celing                          6 non-null      object 
 12  Unnamed: 12                     6 non-

In [80]:
df.isnull().sum()

quantity                           6
price                             12
total sales                       16
Unnamed: 3                        21
Unnamed: 4                        18
modulus(returns the remainder)    20
Unnamed: 6                        16
Unnamed: 7                        24
Unnamed: 8                        25
power                             18
Unnamed: 10                       25
celing                            19
Unnamed: 12                       19
Unnamed: 13                       25
Unnamed: 14                       22
floor                             20
Unnamed: 16                       20
Unnamed: 17                       23
dtype: int64