# Elementwise operations
1.Basic operations
with scalars

In [1]:
import numpy as np
a=np.array([1,2,3,4])


In [3]:
a=a+1
a

array([2, 3, 4, 5])

In [9]:
a=a**2
a

array([ 16,  81, 256, 625], dtype=int32)

All arithmetic operations elementwise

In [11]:
b=np.ones(4)

In [12]:
b

array([1., 1., 1., 1.])

In [13]:
b+1

array([2., 2., 2., 2.])

In [14]:
a-b

array([ 15.,  80., 255., 624.])

In [15]:
a*b

array([ 16.,  81., 256., 625.])

In [16]:
a+b

array([ 17.,  82., 257., 626.])


# Matrix multiplications 

In [17]:
c=np.diag([1,3,5,7])
c

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [18]:
print(c*c)

[[ 1  0  0  0]
 [ 0  9  0  0]
 [ 0  0 25  0]
 [ 0  0  0 49]]


In [21]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  9  0  0]
 [ 0  0 25  0]
 [ 0  0  0 49]]


# comparisions

In [27]:
a=np.array([10,20,30,40])
b=np.array([10,60,30,80])
c=np.array([50,60,70,90])
a==b

array([ True, False,  True, False])

In [28]:
a>b

array([False, False, False, False])

In [29]:
a<=b

array([ True,  True,  True,  True])

In [30]:
#array-wise comparisions
np.array_equal(a,b)

False

In [31]:
np.array_equal(a,c)

False

In [38]:
np.array_equal(a,b)


False

In [39]:
#logical operations


In [40]:
a=np.array([1,1,0,0])
b=np.array([0,1,1,0])

In [41]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [42]:
np.logical_and(a,b)

array([False,  True, False, False])

In [43]:
#transcendental functions

In [47]:
a=np.arange(1,4+1)
a

array([1, 2, 3, 4])

In [48]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [49]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [52]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [53]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [54]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# shape mismatch

In [58]:
a=np.arange(4)
a+np.array([1,3,5,7],[5,5,5,5])

TypeError: Field elements must be 2- or 3-tuples, got '5'

# basic reduction

In [59]:
#computing sums

In [62]:
x=np.array([1,3,5,7])

In [63]:
x


array([1, 3, 5, 7])

In [64]:
sum(x)

16

In [65]:
np.sum(x)

16

In [86]:
#sum by rows and columns
x=np.array([[1,2,3,4],[1,3,5,7]])
y=np.array([[5,10,15,20],[30,40,50,60]])

In [68]:
x

array([[1, 2, 3, 4],
       [1, 3, 5, 7]])

In [70]:
x.sum(axis=0) #columns first dimension

array([ 2,  5,  8, 11])

x.sum(axis=1) # rows ( second dimension)

In [73]:
x.max()

7

In [74]:
x.min()

1

In [76]:
np.min(x)

1

In [78]:
np.argmin(x)

0

In [82]:
x.argmin()#index of min value

0

In [83]:
x.argmax() #index of max value

7

# logical operations

In [87]:
np.all([True,False,True])

False

In [89]:
np.all(y)

True

In [95]:
#Note:can be used for array comparisions
a=np.zeros((50,50))

In [97]:
np.any(a==0)

True

In [99]:
np.all(a!=a)

False

In [102]:
a=np.arange(0,3)
b=np.arange(3,6)
c=np.arange(6,9)

In [104]:
a

array([0, 1, 2])

In [105]:
np.all(((a>b)&(b<=c)))

False

# statistics

TypeError: unsupported operand type(s) for -: 'list' and 'int'