# Element Selection

In [2]:
import numpy as np
matrix=np.random.randint(1,10,(5,5))

In [3]:
matrix

array([[1, 5, 2, 6, 2],
       [5, 7, 4, 5, 8],
       [2, 5, 7, 2, 9],
       [9, 3, 1, 5, 1],
       [1, 9, 3, 7, 8]])

In [14]:
new=matrix[matrix>3]
new

array([5, 6, 5, 7, 4, 5, 8, 5, 7, 9, 9, 5, 9, 7, 8])

In [7]:
new.dtype

dtype('int32')

# NumPy Arrays
 

# python objects:

high-level number objects: integers, floating point
containers: lists (costless insertion and append), dictionaries (fast lookup)
 

# Numpy provides:

extension package to Python for multi-dimensional arrays
closer to hardware (efficiency)
designed for scientific computation (convenience)
Also known as array oriented computing


In [21]:
a=np.array([10,20,30,40])
print(a)
print(np.arange(1,10+1))

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
#list comp
a=list(range(1,50))
a

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [24]:
ans=[]
for i in a:
    if i%2==0:
        
        ans.append(i)
ans

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [30]:
[i for i in range(1,10+1) if i%2==0]


[2, 4, 6, 8, 10]

In [33]:
%timeit b=[i**2 for i in range(1,10)]

2.71 µs ± 9.05 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [34]:
b

[1, 4, 9, 16, 25, 36, 49, 64, 81]

# creating arrays


In [35]:
a=np.array(range(1,10+1))

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
b=np.array(([range(1,10+1)],[range(11,20+1)]))

In [40]:
b

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]])

In [45]:
len(b)

2

In [56]:
a=a.reshape(2,5)

In [57]:
a.shape

(2, 5)

In [58]:
a.size

10

In [59]:
a.ndim

2

In [60]:
#using arrange function
#arange
a=np.arange(20)

In [61]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
#using linspace
a=np.linspace(0,1,2)#start,end,number of points

In [70]:
a

array([0., 1.])

In [74]:
#creating array using diag function
a=np.diag([10,20,30,40,50])

In [75]:

a

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 50]])

In [82]:
#CREAting array using random
#create an array of the given shape and populate it with random sampples from a uniform distribution
a=np.random.rand(4)

In [83]:
a

array([0.14467726, 0.74811605, 0.85046164, 0.9981189 ])

In [95]:
a=np.random.randn(10)

In [96]:
a

array([ 0.21191006, -0.26813617, -1.69401887, -1.48537487,  0.02486266,
       -1.11032095,  0.01075645, -1.50502986, -0.64341705, -0.67012997])