# PYTHON PROGRAMMING

Numpy basics
Built-in methods and functions
Obtain shape, length and type of Numpy arrays
Reshape
Minimum and maximum and their indices
Mathematical Operations
Indexing and slicing
Selection
 

NUMPY BASICS
NumPy is a Linear Algebra Library used for multidimensional arrays
Installation: Use the command window, type: conda install numpy

In [2]:
import numpy as np
list1=[10,20,30,40,50]
list1

[10, 20, 30, 40, 50]

In [2]:
x=np.array(list1)

single dimensional array

In [3]:
x

array([10, 20, 30, 40, 50])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.shape

(5,)

In [ ]:
#multidimensional array

In [6]:
list2=([10,20,30,40,50],[60,70,80,90,100])
list2
y=np.array(list2)

In [7]:
y.shape

(2, 5)

In [8]:
y

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

# built in methods and functions

In [9]:
#random.rand() print random number between 0to1
z=np.random.rand(5)
z

array([0.42187024, 0.47100988, 0.17638855, 0.52706166, 0.16880851])

In [34]:
p=np.random.randint(0,5)

In [46]:
p

3

In [49]:
p=np.random.randint(0,5+1,2)
p

array([5, 3])

In [50]:
q=np.arange(1,50+1)

In [51]:
q

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [52]:
q=np.arange(0,50+1,5)

In [45]:
q

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [4]:
q=np.eye(5)

In [57]:
q

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
#arrays of ones
x=np.ones(15)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
x=np.ones((15,15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [61]:
x.shape

(15, 15)

In [62]:
x=np.zeros(15)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
x.shape

(15,)

In [74]:
#get length

len(x)

15

In [65]:
#get shape
q.shape

(5, 5)

In [6]:
a=np.array([10,20,30,40])
a.shape

(4,)

In [7]:
#reshape 
a.reshape(2,2)

array([[10, 20],
       [30, 40]])

In [80]:
#max and min values and their index
a.min()

10

In [81]:
a.max()

40

In [82]:
a.dtype

dtype('int32')

In [88]:
x=np.array((10,2,3))
print(x)
type(x)

[10  2  3]


numpy.ndarray

In [85]:
x=np.array({10,2,20,40})
x

array({40, 10, 2, 20}, dtype=object)

In [86]:
x.min()

{2, 10, 20, 40}

In [89]:
#obtain the index of max value
a.argmax()

3

In [90]:
#obtain the index of min value
a.argmin()

0

# mathematical operation

In [100]:
a=np.array(([10,20,30,40],[50,60,70,80]))
b=np.array(([10,20,30,40],[70,90,50,80]))


In [101]:
y=a*2
y

array([[ 20,  40,  60,  80],
       [100, 120, 140, 160]])

In [102]:
y=a*b

In [103]:
y

array([[ 100,  400,  900, 1600],
       [3500, 5400, 3500, 6400]])

# elements slicing and indexing

In [104]:
x=np.random.randint(1,10+1,10)

In [105]:
x

array([ 5,  9,  6,  5,  6, 10,  5,  7,  5, 10])

In [106]:
x[3]

5

In [107]:
x[0:3]

array([5, 9, 6])

In [108]:
#broadcasting  altering several values in a numpy array at once

In [109]:
x[0:6]=10
x

array([10, 10, 10, 10, 10, 10,  5,  7,  5, 10])

In [111]:
#(5,5) is the shape of matrix
matrix=np.random.randint(1,10,(5,5))
matrix

array([[6, 8, 6, 3, 4],
       [7, 2, 7, 9, 3],
       [4, 7, 3, 9, 4],
       [8, 6, 2, 6, 8],
       [7, 5, 9, 9, 2]])

In [116]:
mini_matrix=matrix[:,:2]
mini_matrix

array([[6, 8],
       [7, 2],
       [4, 7],
       [8, 6],
       [7, 5]])

In [117]:
mini_matrix=matrix[:,2:]
mini_matrix

array([[6, 3, 4],
       [7, 9, 3],
       [3, 9, 4],
       [2, 6, 8],
       [9, 9, 2]])